### ISSUE TITLE
Error during POD install

### ISSUE THREAD

**Issue by dominwong4** [skiprco/adyen_flutter#2]
[!] Unable to determine Swift version for the following pods:

- `adyen_flutter` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integra
te this pod.

[!] Automatically assigning platform `ios` with version `10.3` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by dominwong4** [comment]
Solution:
Create Empty Switft File in Runner Target.

Next Problem you may face:
CardEncryptor has no member of environment

Solution: 
add pod 'Adyen', '2.5.0' into the Podfile, because it will install 3.0.0 if not pointing to specific version

if you are faceing .h not found

add

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end

**Comment by loveuqian** [comment]
@dominwong4 , thanks for your solution
i follow all your solution, but it still cannot run
error: type 'CardEncryptor' has no member 'Environment'
can u help me again?

**Comment by dominwong4** [comment]
How about clear and rebuild.

Adyen package is so weird and I only listing the issue and solution I have found.

**Comment by ludoviclaffineur** [comment]
Hello all!

This plug in is still in a unstable state. 
We will also have a closer look at it in a near future. In the meantime, any PR that solves this issue is welcome!

Thanks again for your contribution

**Comment by loveuqian** [comment]
@dominwong4 
Finally, I found my problem, thanks for your solution!
